 
No internet connection... Press any key to resume ... 
COUNTRIES=AUT
SCENARIOS=high-vaccination scenario-comparison
 
 
############################################################################
RUNNING ANALYSIS (WEB)
############################################################################
 
 
[jupytext] Reading web-run-sim.ipynb in format ipynb
[jupytext] Updating 'web-run-sim.py'
[jupytext] Reading web-meta.ipynb in format ipynb
[jupytext] Loading 'web-meta.py'
[jupytext] Updating 'web-meta.ipynb'
[jupytext] Updating 'web-meta.py'
[jupytext] Reading web-index.ipynb in format ipynb
[jupytext] Updating 'web-index.py'
[jupytext] Reading web-country-scen.ipynb in format ipynb
[jupytext] Updating 'web-country-scen.py'
[jupytext] Reading web-country-comp.ipynb in format ipynb
[jupytext] Updating 'web-country-comp.py'
 
RUNNING ANALYSIS FOR COUNTRY: AUT...
 
Input Notebook:  ./web-run-sim_.ipynb
Output Notebook: ./web-run-sim_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpjht9ahu0'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpgpn57yre'
Executing:   0%|          | 0/17 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   6%|▌         | 1/17 [00:00<00:14,  1.13cell/s]Executing:  24%|██▎       | 4/17 [00:00<00:08,  1.59cell/s]Executing:  35%|███▌      | 6/17 [00:05<00:11,  1.07s/cell]Executing:  35%|███▌      | 6/17 [00:05<00:10,  1.06cell/s]
Traceback (most recent call last):
  File "/home/jb/.local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/cli.py", line 267, in papermill
    execution_timeout=execution_timeout,
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-5-77a8edef756d> in <module>
----> 1 import simulation
      2 
      3 import ccodes
      4 
      5 cname_f = ccodes.ct_codes[cname]

~/git/covid-19-sird/sim/output/src/simulation.py in <module>
    202 
    203 import models
--> 204 import COVID_19_ANALYSIS as C19
    205 import COVID_19_ANALYSIS_incl as C19_incl   # not used
    206 import ccodes

~/git/covid-19-sird/sim/output/src/COVID_19_ANALYSIS.py in <module>
  52924 
  52925 
> 52926 def get_owid_group_data(cname, c_start_date=date(2021,1,1), fyle = '', colname='', group_colname='', data_dir_pth='', endtime=0):
  52927 
  52928     dbg = 1

NameError: name 'date' is not defined

[NbConvertApp] Converting notebook ./web-run-sim_.ipynb to html
[NbConvertApp] Writing 572776 bytes to web-run-sim_.html
 
SCENARIO: high-vaccination...
 
Input Notebook:  ./web-country-scen_.ipynb
Output Notebook: ./web-country-scen_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmp0unyq8wv'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmp8iwqkspm'
Executing:   0%|          | 0/42 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   2%|▏         | 1/42 [00:00<00:40,  1.01cell/s]Executing:   7%|▋         | 3/42 [00:01<00:27,  1.41cell/s]Executing:  12%|█▏        | 5/42 [00:01<00:19,  1.94cell/s]Executing:  17%|█▋        | 7/42 [00:01<00:13,  2.50cell/s]Executing:  21%|██▏       | 9/42 [00:01<00:09,  3.36cell/s]Executing:  26%|██▌       | 11/42 [00:01<00:07,  4.38cell/s]Executing:  31%|███       | 13/42 [00:02<00:09,  3.22cell/s]Executing:  36%|███▌      | 15/42 [00:02<00:06,  4.24cell/s]Executing:  40%|████      | 17/42 [00:02<00:04,  5.45cell/s]Executing:  45%|████▌     | 19/42 [00:04<00:07,  3.21cell/s]Executing:  45%|████▌     | 19/42 [00:04<00:05,  4.02cell/s]
Traceback (most recent call last):
  File "/home/jb/.local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/cli.py", line 267, in papermill
    execution_timeout=execution_timeout,
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-d2153f43af6d> in <module>
     20             # The protocol version used is detected automatically, so we do not
     21             # have to specify it.
---> 22             sim_Countries_cname = pickle.load(f)
     23 
     24 

~/git/covid-19-sird/sim/output/src/simulation.py in <module>
    202 
    203 import models
--> 204 import COVID_19_ANALYSIS as C19
    205 import COVID_19_ANALYSIS_incl as C19_incl   # not used
    206 import ccodes

~/git/covid-19-sird/sim/output/src/COVID_19_ANALYSIS.py in <module>
  52924 
  52925 
> 52926 def get_owid_group_data(cname, c_start_date=date(2021,1,1), fyle = '', colname='', group_colname='', data_dir_pth='', endtime=0):
  52927 
  52928     dbg = 1

NameError: name 'date' is not defined

 
SCENARIO: scenario-comparison...
 
Input Notebook:  ./web-country-scen_.ipynb
Output Notebook: ./web-country-scen_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpr3q_gluf'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmp7ndy8c19'
Executing:   0%|          | 0/42 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   2%|▏         | 1/42 [00:00<00:37,  1.11cell/s]Executing:   7%|▋         | 3/42 [00:01<00:25,  1.53cell/s]Executing:  12%|█▏        | 5/42 [00:01<00:17,  2.11cell/s]Executing:  17%|█▋        | 7/42 [00:01<00:13,  2.69cell/s]Executing:  21%|██▏       | 9/42 [00:01<00:09,  3.56cell/s]Executing:  26%|██▌       | 11/42 [00:01<00:06,  4.62cell/s]Executing:  31%|███       | 13/42 [00:02<00:08,  3.50cell/s]Executing:  36%|███▌      | 15/42 [00:02<00:05,  4.53cell/s]Executing:  40%|████      | 17/42 [00:02<00:04,  5.71cell/s]Executing:  45%|████▌     | 19/42 [00:04<00:07,  3.05cell/s]Executing:  45%|████▌     | 19/42 [00:04<00:05,  4.02cell/s]
Traceback (most recent call last):
  File "/home/jb/.local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/cli.py", line 267, in papermill
    execution_timeout=execution_timeout,
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-d2153f43af6d> in <module>
     20             # The protocol version used is detected automatically, so we do not
     21             # have to specify it.
---> 22             sim_Countries_cname = pickle.load(f)
     23 
     24 

~/git/covid-19-sird/sim/output/src/simulation.py in <module>
    202 
    203 import models
--> 204 import COVID_19_ANALYSIS as C19
    205 import COVID_19_ANALYSIS_incl as C19_incl   # not used
    206 import ccodes

~/git/covid-19-sird/sim/output/src/COVID_19_ANALYSIS.py in <module>
  52924 
  52925 
> 52926 def get_owid_group_data(cname, c_start_date=date(2021,1,1), fyle = '', colname='', group_colname='', data_dir_pth='', endtime=0):
  52927 
  52928     dbg = 1

NameError: name 'date' is not defined

 
CREATING COUNTRY COMPARISONS...
 
Input Notebook:  ./web-country-comp_.ipynb
Output Notebook: ./web-country-comp_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpyct6oi3d'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpxijl15ns'
Executing:   0%|          | 0/41 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   2%|▏         | 1/41 [00:00<00:37,  1.06cell/s]Executing:   7%|▋         | 3/41 [00:01<00:25,  1.48cell/s]Executing:  12%|█▏        | 5/41 [00:01<00:18,  1.96cell/s]Executing:  17%|█▋        | 7/41 [00:01<00:12,  2.68cell/s]Executing:  22%|██▏       | 9/41 [00:01<00:08,  3.60cell/s]Executing:  27%|██▋       | 11/41 [00:02<00:09,  3.16cell/s]Executing:  29%|██▉       | 12/41 [00:02<00:11,  2.45cell/s]Executing:  32%|███▏      | 13/41 [00:03<00:09,  2.89cell/s]Executing:  34%|███▍      | 14/41 [00:03<00:08,  3.31cell/s]Executing:  37%|███▋      | 15/41 [00:03<00:07,  3.64cell/s]Executing:  39%|███▉      | 16/41 [00:03<00:06,  4.02cell/s]Executing:  41%|████▏     | 17/41 [00:03<00:05,  4.34cell/s]Executing:  44%|████▍     | 18/41 [00:04<00:05,  4.58cell/s]Executing:  46%|████▋     | 19/41 [00:04<00:04,  4.76cell/s]Executing:  49%|████▉     | 20/41 [00:04<00:04,  4.88cell/s]Executing:  51%|█████     | 21/41 [00:05<00:10,  1.82cell/s]Executing:  51%|█████     | 21/41 [00:07<00:06,  2.87cell/s]
Traceback (most recent call last):
  File "/home/jb/.local/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jb/.local/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/cli.py", line 267, in papermill
    execution_timeout=execution_timeout,
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/home/jb/.local/lib/python3.7/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [18]":
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-18-93c0b62bde6b> in <module>
     27             # The protocol version used is detected automatically, so we do not
     28             # have to specify it.
---> 29             sim_Countries_cname[c] = pickle.load(f)
     30 
     31 

~/git/covid-19-sird/sim/output/src/simulation.py in <module>
    202 
    203 import models
--> 204 import COVID_19_ANALYSIS as C19
    205 import COVID_19_ANALYSIS_incl as C19_incl   # not used
    206 import ccodes

~/git/covid-19-sird/sim/output/src/COVID_19_ANALYSIS.py in <module>
  52924 
  52925 
> 52926 def get_owid_group_data(cname, c_start_date=date(2021,1,1), fyle = '', colname='', group_colname='', data_dir_pth='', endtime=0):
  52927 
  52928     dbg = 1

NameError: name 'date' is not defined

 
CREATING INDEX...
 
Input Notebook:  ./web-index_.ipynb
Output Notebook: ./web-index_.ipynb
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/Grammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/Grammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpuasm7qug'
Generating grammar tables from /home/jb/.local/lib/python3.7/site-packages/blib2to3/PatternGrammar.txt
Writing grammar tables to /home/jb/.cache/black/20.8b1/PatternGrammar3.7.3.final.0.pickle
Writing failed: [Errno 2] No such file or directory: '/home/jb/.cache/black/20.8b1/tmpsg2aagsj'
Executing:   0%|          | 0/20 [00:00<?, ?cell/s]Executing notebook with kernel: python3
Executing:   5%|▌         | 1/20 [00:00<00:16,  1.16cell/s]Executing:  25%|██▌       | 5/20 [00:00<00:09,  1.64cell/s]Executing:  40%|████      | 8/20 [00:01<00:05,  2.29cell/s]Executing:  60%|██████    | 12/20 [00:01<00:02,  3.17cell/s]Executing:  80%|████████  | 16/20 [00:01<00:00,  4.35cell/s]Executing: 100%|██████████| 20/20 [00:01<00:00,  5.88cell/s]Executing: 100%|██████████| 20/20 [00:01<00:00, 11.43cell/s]
[NbConvertApp] Converting notebook web-index_.ipynb to notebook
[NbConvertApp] Writing 24925 bytes to web-index_.ipynb
[NbConvertApp] Converting notebook web-country-scen_.ipynb to notebook
[NbConvertApp] Writing 153601 bytes to web-country-scen_.ipynb
 
 
############################################################################
END OF ANALYSIS (WEB)
############################################################################
 
 
 
RUNTIME: 48 s (0 m)
 
